### PR TITLE
feat(lib): add plugin that can execute arbitrary shell commands from manifest

### PR DESCRIPTION
**Pull request by alexzurbonsen**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request
A plugin that can execute shell commands that are provided in the manifest file.

Can be handy in certain situations, example see the `README.md` in #52.

### CODE REVIEW

**Comment by jmcook1186** [comment]
HI @alexzurbonsen we already have a plugin that does this in `if-plugins`. We're very enthusiastic about people hosting their own alternative versions in separate repositories though - in fact that's kind of the vision for the IF. So, we'll probably close this out but encourage you to move it to it's own repository if you want to use it in preference to the version in `if-plugins`.

**Comment by alexzurbonsen** [comment]
Hi @jmcook1186, thanks for your feedback.

A short explanation: I think the `Shell` plugin from if-plugins is a bit different. It is able to run external plugins and passes the entire inputs array to that plugin.

The plugin in this PR is just a simple command execution on every single input of the inputs array.

Initially, I thought `Shell` from if-plugins could do exactly that, but it doesn't. Thus, I also opened https://github.com/Green-Software-Foundation/if-plugins/pull/57 to clarify this.

But of course, I don't mind if you close this one out. I just thought it adds something valueable.

**Comment by jmcook1186** [comment]
oh i see -  ok i'll add it to the list of topics for our PR triage call and get back to you. Things are calmer this week so we will get through more of your PRs.

**Comment by alexzurbonsen** [comment]
Sounds good. Thanks. And nevermind, I figured that you are quiet busy these days. And most PRs are not urgend I guess.

**Comment by jmcook1186** [comment]
Hi - we would prefer new plugins to be hosted in external Github repositories. This seems useful but not likely to be part of our standard library - better to maintain it in a separate repo. We want to make it so lots of plugins are discoverable, but only a core set of generic plugins are in our maintained library.

**Comment by alexzurbonsen** [comment]
Hi @jmcook1186, thanks for your feedback. I understand that now what your vision for the plugin landscape is. I will see that I make them available in a suitable way.

**Pull request closed without merging**
