### PR TITLE
feat: plugins and manifest for measuring a webpage

### PR DESCRIPTION
**Pull request by alexzurbonsen**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request
Plugins for measuring a webpage. Plus additional plugin for looking up green hosting. Plus plugin for measuring time (also opened a PR for that separately). 

One based on puppeteer.
The other one on lighthouse.

There is also an example manifest file for the puppeteer plugin.

Tests for the measurement plugins are still missing.

More infos to follow.

### CODE REVIEW

**Comment by jmcook1186** [comment]
Hi @alexzurbonsen thanks for this, but we are unlikely to merge this into if-unofficial-plugins. The reason is that ultimately want to remove this repo entirely and encourage people to build new plugins in their own repositories separate from the IF. This is because the vision is to have thousands of plugins and we don't want the core team's ability to maintain them to be a bottleneck on ecosystem growth. So, in summary I encourage you to develop this in your own repo. This is exactly the kind of plugin we want people to host externally to IF.

**Comment by alexzurbonsen** [comment]
@jmcook1186 sure, makes sense to me. I also wasn't sure what you idea is on how this should be handled. There is also a hackathon issue for this and I wanted to share what I worked on so far with the group. Thus, it is still a draft and will remain one.

**Comment by alexzurbonsen** [comment]
What's the vision on how people should find existing plugins by the way? Is there some sort of registry?

**Comment by jmcook1186** [comment]
Yes, there will be - we were just sketching out some plans for this earlier in the week. Without committing to a specific path right now, we anticipate maintaining some kind of simple centralized list or explorer for other people's plugins. (tbh right now there aren't very many, so this is a problem for after the hackathon when the available set is much larger)

**Comment by alexzurbonsen** [comment]
Thanks for the info. That is good to know. Sorry, if I missed this piece of information in the docs somewhere.

**Pull request closed without merging**
